### ISSUE TITLE
[REQUEST] Let us change UI color

### ISSUE THREAD

**Issue by KoleckOLP** [eclipsedteam/osu-trigen#13]
The pink of the UI is nice and fits osu but I can imagine dark blue or other colors would fit better when you are actually using the software.

there are 2 ways about it a config file with UI_color=#2376F3

or similar color picker like the one for triangles and background (you should be able to hide them and reopen)

I would be cool if all ui element could be minimized into tiny buttons that open them back up.

**Comment by Tanza3D** [comment]
The way this'd probably would is that it'd be a button in the info & credits menu to allow you to open up a pop-up colour picker to set the colour in, then that'll auto-load next time the app starts. 

"I would be cool if all ui element could be minimized into tiny buttons that open them back up." This was already planned, but was scrapped for multiple reasons, but due to the way the panels are going to work after i make the colour changeable, it'll most likely work perfectly after this. Hopefully for either 1.3 or 1.4.

**Comment by Tanza3D** [comment]
Done.
